export const USERNAME_SAVE = 'USERNAME_SAVE'
export const USER_CONNECT = 'USER_CONNECTED'
export const USER_DISCONNECT = 'USER_DISCONNECT'

export const USER_SELF_TYPING = 'USER_SELF_TYPING'
export const USER_SELF_NOT_TYPING = 'USER_SELF_NOT_TYPING'

export const USER_OTHER_TYPING = 'USER_OTHER_TYPING'
export const USER_OTHER_NOT_TYPING = 'USER_OTHER_NOT_TYPING'

export const MESSAGE_ADD = 'MESSAGE_ADD'

export const SOCKET_MESSAGE_SEND = 'SOCKET_MESSAGE_SEND'
export const SOCKET_CONNECT = 'SOCKET_CONNECT'
export const SOCKET_INIT = 'SOCKET_INIT'